/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ledgoes;

import java.awt.Color;
import javax.swing.BorderFactory;

/**
 *
 * @author Stephen
 */
public class LEDgoesInterface extends javax.swing.JFrame {

    /**
     * Creates new form LEDgoesInterface
     */
    public LEDgoesInterface() {
        initComponents();
        App.multiplexed = true;
        App.populate();
        panelRows.setBorder(BorderFactory.createTitledBorder("Rows"));
        App.messages = new String[10];
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCOM1Connect = new javax.swing.JButton();
        tabs = new javax.swing.JTabbedPane();
        tabRawText = new javax.swing.JPanel();
        descRawText = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        tabTwitterFeed = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtTwitter = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        tabAnimation = new javax.swing.JPanel();
        rbChooseImg = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        rbChooseGIF = new javax.swing.JRadioButton();
        txtImgPath = new javax.swing.JTextField();
        txtGIFPath = new javax.swing.JTextField();
        rbChooseAVI = new javax.swing.JRadioButton();
        txtAVIPath = new javax.swing.JTextField();
        btnChooseImg = new javax.swing.JButton();
        btnChooseGIF = new javax.swing.JButton();
        btnChooseAVI = new javax.swing.JButton();
        btnAnimSend = new javax.swing.JButton();
        COMChoice1 = new javax.swing.JComboBox();
        panelRows = new javax.swing.JPanel();
        rowCount = new javax.swing.JSpinner();
        isMultiplexed = new javax.swing.JCheckBox();
        lblSpeed = new javax.swing.JLabel();
        lblCOMPort1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        lblCOMPort2 = new javax.swing.JLabel();
        COMChoice2 = new javax.swing.JComboBox();
        btnCOM2Connect = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LEDgoes PC Interface");
        setName("LEDgoes PC Interface"); // NOI18N

        btnCOM1Connect.setBackground(new java.awt.Color(0, 255, 0));
        btnCOM1Connect.setText("Connect");
        btnCOM1Connect.setName("1"); // NOI18N
        btnCOM1Connect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCOM1ConnectMouseClicked(evt);
            }
        });

        tabs.setName("Boop"); // NOI18N

        descRawText.setText("Enter a message in the box at the bottom, then hit Push.  It will appear in the list below.");

        jLabel3.setText("Message:");

        jScrollPane1.setViewportView(jEditorPane1);

        javax.swing.GroupLayout tabRawTextLayout = new javax.swing.GroupLayout(tabRawText);
        tabRawText.setLayout(tabRawTextLayout);
        tabRawTextLayout.setHorizontalGroup(
            tabRawTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabRawTextLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabRawTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(descRawText)
                    .addGroup(tabRawTextLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        tabRawTextLayout.setVerticalGroup(
            tabRawTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabRawTextLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(descRawText)
                .addGap(18, 18, 18)
                .addGroup(tabRawTextLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(130, Short.MAX_VALUE))
        );

        tabs.addTab("Raw Text", tabRawText);
        tabRawText.getAccessibleContext().setAccessibleName("tabRawText");

        jLabel1.setText("Twitter feed:");

        jButton1.setText("Go!");

        javax.swing.GroupLayout tabTwitterFeedLayout = new javax.swing.GroupLayout(tabTwitterFeed);
        tabTwitterFeed.setLayout(tabTwitterFeedLayout);
        tabTwitterFeedLayout.setHorizontalGroup(
            tabTwitterFeedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabTwitterFeedLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTwitter, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                .addContainerGap())
        );
        tabTwitterFeedLayout.setVerticalGroup(
            tabTwitterFeedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabTwitterFeedLayout.createSequentialGroup()
                .addContainerGap(143, Short.MAX_VALUE)
                .addGroup(tabTwitterFeedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTwitter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(46, 46, 46))
        );

        tabs.addTab("Twitter Feed", tabTwitterFeed);
        tabTwitterFeed.getAccessibleContext().setAccessibleName("tabTwitterFeed");

        rbChooseImg.setLabel("Image Folder:");

        jLabel2.setText("Select a folder containing bitmap image frames, an animated GIF image, or an AVI movie.");

        rbChooseGIF.setText("GIF Path:");
        rbChooseGIF.setEnabled(false);

        txtImgPath.setToolTipText("[Optional] Path to a folder containing frames of an animation, in BMP format");

        txtGIFPath.setEditable(false);
        txtGIFPath.setText("Coming soon");
        txtGIFPath.setToolTipText("[Optional] Path to an animated GIF file");

        rbChooseAVI.setText("AVI Path:");
        rbChooseAVI.setEnabled(false);

        txtAVIPath.setEditable(false);
        txtAVIPath.setText("Coming soon");
        txtAVIPath.setToolTipText("[Optional] Path to an animated GIF file");

        btnChooseImg.setText("Choose...");

        btnChooseGIF.setText("Choose...");
        btnChooseGIF.setEnabled(false);

        btnChooseAVI.setText("Choose...");
        btnChooseAVI.setEnabled(false);

        btnAnimSend.setText("Send Animation");

        javax.swing.GroupLayout tabAnimationLayout = new javax.swing.GroupLayout(tabAnimation);
        tabAnimation.setLayout(tabAnimationLayout);
        tabAnimationLayout.setHorizontalGroup(
            tabAnimationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabAnimationLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tabAnimationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tabAnimationLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(tabAnimationLayout.createSequentialGroup()
                        .addGroup(tabAnimationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(tabAnimationLayout.createSequentialGroup()
                                .addComponent(rbChooseImg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtImgPath, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(tabAnimationLayout.createSequentialGroup()
                                .addGroup(tabAnimationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rbChooseAVI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(rbChooseGIF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(tabAnimationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtAVIPath, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtGIFPath, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(tabAnimationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tabAnimationLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(btnChooseImg))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tabAnimationLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(tabAnimationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnChooseGIF, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnChooseAVI, javax.swing.GroupLayout.Alignment.TRAILING))))))
                .addContainerGap())
            .addGroup(tabAnimationLayout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(btnAnimSend)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        tabAnimationLayout.setVerticalGroup(
            tabAnimationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tabAnimationLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(tabAnimationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbChooseImg)
                    .addComponent(txtImgPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChooseImg))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tabAnimationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbChooseGIF)
                    .addComponent(txtGIFPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChooseGIF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tabAnimationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbChooseAVI)
                    .addComponent(txtAVIPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnChooseAVI))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(btnAnimSend)
                .addContainerGap())
        );

        tabs.addTab("Animation", tabAnimation);

        COMChoice1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "(Select)" }));

        rowCount.setModel(new javax.swing.SpinnerNumberModel(1, 1, 64, 1));

        isMultiplexed.setSelected(true);
        isMultiplexed.setLabel("Multiplexed");
        isMultiplexed.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                isMultiplexedStateChanged(evt);
            }
        });

        javax.swing.GroupLayout panelRowsLayout = new javax.swing.GroupLayout(panelRows);
        panelRows.setLayout(panelRowsLayout);
        panelRowsLayout.setHorizontalGroup(
            panelRowsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRowsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRowsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rowCount)
                    .addGroup(panelRowsLayout.createSequentialGroup()
                        .addComponent(isMultiplexed)
                        .addGap(0, 3, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelRowsLayout.setVerticalGroup(
            panelRowsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRowsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rowCount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(isMultiplexed)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        lblSpeed.setText("Speed (bps):");

        lblCOMPort1.setText("Row 1 COM Port:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "9600", "19200", "38400", "57600", "115200", "230400", "460800" }));

        lblCOMPort2.setText("Row 2 COM Port:");
        lblCOMPort2.setEnabled(false);

        COMChoice2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "(Select)" }));
        COMChoice2.setEnabled(false);

        btnCOM2Connect.setBackground(new java.awt.Color(0, 255, 0));
        btnCOM2Connect.setText("Connect");
        btnCOM2Connect.setEnabled(false);
        btnCOM2Connect.setName("2"); // NOI18N
        btnCOM2Connect.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCOM2ConnectMouseClicked(evt);
            }
        });

        jMenuBar1.setEnabled(false);

        jMenu1.setText("Help");

        jMenuItem1.setText("About...");
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tabs)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelRows, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblCOMPort1)
                                    .addComponent(lblSpeed))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(COMChoice1, 0, 167, Short.MAX_VALUE)
                                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblCOMPort2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(COMChoice2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCOM1Connect)
                            .addComponent(btnCOM2Connect))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelRows, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSpeed)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCOMPort1)
                            .addComponent(COMChoice1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCOM1Connect))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCOMPort2)
                            .addComponent(COMChoice2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCOM2Connect))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tabs)
                .addContainerGap())
        );

        tabs.getAccessibleContext().setAccessibleName("tabs");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCOM1ConnectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCOM1ConnectMouseClicked
        comConnect(evt);
    }//GEN-LAST:event_btnCOM1ConnectMouseClicked

    private void btnCOM2ConnectMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCOM2ConnectMouseClicked
        comConnect(evt);
    }//GEN-LAST:event_btnCOM2ConnectMouseClicked

    private void comConnect(java.awt.event.MouseEvent evt) {
        javax.swing.JButton btn = (javax.swing.JButton) evt.getComponent();
        if (btn.getBackground().equals(Color.GREEN)) {
            App.SerialPortOpen(evt);
        } else {
            App.SerialPortClose(evt);
        }
    }
    
    private void isMultiplexedStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_isMultiplexedStateChanged
        boolean state = (isMultiplexed.isSelected()) ? false : true;
        btnCOM2Connect.setEnabled(state);
        COMChoice2.setEnabled(state);
        lblCOMPort2.setEnabled(state);
        App.multiplexed = !state;
    }//GEN-LAST:event_isMultiplexedStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LEDgoesInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LEDgoesInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LEDgoesInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LEDgoesInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LEDgoesInterface().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JComboBox COMChoice1;
    public static javax.swing.JComboBox COMChoice2;
    private javax.swing.JButton btnAnimSend;
    public static javax.swing.JButton btnCOM1Connect;
    public static javax.swing.JButton btnCOM2Connect;
    private javax.swing.JButton btnChooseAVI;
    private javax.swing.JButton btnChooseGIF;
    private javax.swing.JButton btnChooseImg;
    private javax.swing.JLabel descRawText;
    public static javax.swing.JCheckBox isMultiplexed;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCOMPort1;
    public javax.swing.JLabel lblCOMPort2;
    private javax.swing.JLabel lblSpeed;
    private javax.swing.JPanel panelRows;
    private javax.swing.JRadioButton rbChooseAVI;
    private javax.swing.JRadioButton rbChooseGIF;
    private javax.swing.JRadioButton rbChooseImg;
    public static javax.swing.JSpinner rowCount;
    private javax.swing.JPanel tabAnimation;
    private javax.swing.JPanel tabRawText;
    private javax.swing.JPanel tabTwitterFeed;
    private static javax.swing.JTabbedPane tabs;
    private javax.swing.JTextField txtAVIPath;
    private javax.swing.JTextField txtGIFPath;
    private javax.swing.JTextField txtImgPath;
    private javax.swing.JTextField txtTwitter;
    // End of variables declaration//GEN-END:variables
}
