# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Stephen\Documents\LEDgoes PC Interface.ui'
#
# Created: Thu Mar 06 23:54:21 2014
#      by: PyQt5 UI code generator 5.1.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(543, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridGroupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.gridGroupBox.setGeometry(QtCore.QRect(210, 20, 321, 161))
        self.gridGroupBox.setObjectName("gridGroupBox")
        self.commLayout = QtWidgets.QGridLayout(self.gridGroupBox)
        self.commLayout.setContentsMargins(10, 10, 10, 10)
        self.commLayout.setObjectName("commLayout")
        self.selRow2COM = QtWidgets.QComboBox(self.gridGroupBox)
        self.selRow2COM.setEnabled(False)
        self.selRow2COM.setObjectName("selRow2COM")
        self.commLayout.addWidget(self.selRow2COM, 2, 1, 1, 1)
        self.selRow1COM = QtWidgets.QComboBox(self.gridGroupBox)
        self.selRow1COM.setObjectName("selRow1COM")
        self.commLayout.addWidget(self.selRow1COM, 1, 1, 1, 1)
        self.lblRow2COMPort = QtWidgets.QLabel(self.gridGroupBox)
        self.lblRow2COMPort.setEnabled(False)
        self.lblRow2COMPort.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblRow2COMPort.setObjectName("lblRow2COMPort")
        self.commLayout.addWidget(self.lblRow2COMPort, 2, 0, 1, 1)
        self.lblRow1COMPort = QtWidgets.QLabel(self.gridGroupBox)
        self.lblRow1COMPort.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblRow1COMPort.setObjectName("lblRow1COMPort")
        self.commLayout.addWidget(self.lblRow1COMPort, 1, 0, 1, 1)
        self.selSpeed = QtWidgets.QComboBox(self.gridGroupBox)
        self.selSpeed.setObjectName("selSpeed")
        self.commLayout.addWidget(self.selSpeed, 0, 1, 1, 1)
        self.lblSpeed = QtWidgets.QLabel(self.gridGroupBox)
        self.lblSpeed.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblSpeed.setObjectName("lblSpeed")
        self.commLayout.addWidget(self.lblSpeed, 0, 0, 1, 1)
        self.btnConnectRow1 = QtWidgets.QPushButton(self.gridGroupBox)
        self.btnConnectRow1.setObjectName("btnConnectRow1")
        self.commLayout.addWidget(self.btnConnectRow1, 1, 2, 1, 1)
        self.btnConnectRow2 = QtWidgets.QPushButton(self.gridGroupBox)
        self.btnConnectRow2.setEnabled(False)
        self.btnConnectRow2.setObjectName("btnConnectRow2")
        self.commLayout.addWidget(self.btnConnectRow2, 2, 2, 1, 1)
        self.lblPlaceholder = QtWidgets.QLabel(self.gridGroupBox)
        self.lblPlaceholder.setText("")
        self.lblPlaceholder.setObjectName("lblPlaceholder")
        self.commLayout.addWidget(self.lblPlaceholder, 3, 0, 1, 1)
        self.btnChangeBaudRate = QtWidgets.QPushButton(self.gridGroupBox)
        self.btnChangeBaudRate.setObjectName("btnChangeBaudRate")
        self.commLayout.addWidget(self.btnChangeBaudRate, 0, 2, 1, 1)
        self.commLayout.setColumnStretch(1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 190, 521, 361))
        self.tabWidget.setObjectName("tabWidget")
        self.tabRawText = QtWidgets.QWidget()
        self.tabRawText.setObjectName("tabRawText")
        self.lblRawTextInstrs = QtWidgets.QLabel(self.tabRawText)
        self.lblRawTextInstrs.setGeometry(QtCore.QRect(20, 20, 471, 31))
        self.lblRawTextInstrs.setWordWrap(True)
        self.lblRawTextInstrs.setObjectName("lblRawTextInstrs")
        self.txtMessage = QtWidgets.QTextEdit(self.tabRawText)
        self.txtMessage.setGeometry(QtCore.QRect(20, 300, 311, 21))
        self.txtMessage.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtMessage.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtMessage.setObjectName("txtMessage")
        self.btnPush = QtWidgets.QPushButton(self.tabRawText)
        self.btnPush.setGeometry(QtCore.QRect(340, 300, 75, 23))
        self.btnPush.setObjectName("btnPush")
        self.btnReplace = QtWidgets.QPushButton(self.tabRawText)
        self.btnReplace.setGeometry(QtCore.QRect(420, 300, 75, 23))
        self.btnReplace.setObjectName("btnReplace")
        self.tabWidget.addTab(self.tabRawText, "")
        self.tabTwitter = QtWidgets.QWidget()
        self.tabTwitter.setObjectName("tabTwitter")
        self.lblComingSoon1 = QtWidgets.QLabel(self.tabTwitter)
        self.lblComingSoon1.setGeometry(QtCore.QRect(30, 30, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lblComingSoon1.setFont(font)
        self.lblComingSoon1.setObjectName("lblComingSoon1")
        self.tabWidget.addTab(self.tabTwitter, "")
        self.tabAnimation = QtWidgets.QWidget()
        self.tabAnimation.setObjectName("tabAnimation")
        self.lblComingSoon2 = QtWidgets.QLabel(self.tabAnimation)
        self.lblComingSoon2.setGeometry(QtCore.QRect(30, 30, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lblComingSoon2.setFont(font)
        self.lblComingSoon2.setObjectName("lblComingSoon2")
        self.tabWidget.addTab(self.tabAnimation, "")
        self.tabFirmware = QtWidgets.QWidget()
        self.tabFirmware.setObjectName("tabFirmware")
        self.lblFirmwareDescription = QtWidgets.QLabel(self.tabFirmware)
        self.lblFirmwareDescription.setGeometry(QtCore.QRect(10, 10, 491, 16))
        self.lblFirmwareDescription.setObjectName("lblFirmwareDescription")
        self.gridLayoutWidget = QtWidgets.QWidget(self.tabFirmware)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 40, 491, 145))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.btnDecrementChipID = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnDecrementChipID.setObjectName("btnDecrementChipID")
        self.gridLayout.addWidget(self.btnDecrementChipID, 2, 0, 1, 1)
        self.lblDecrementChipOf = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lblDecrementChipOf.setObjectName("lblDecrementChipOf")
        self.gridLayout.addWidget(self.lblDecrementChipOf, 2, 1, 1, 1)
        self.btnIncrementChipID = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnIncrementChipID.setObjectName("btnIncrementChipID")
        self.gridLayout.addWidget(self.btnIncrementChipID, 1, 0, 1, 1)
        self.lblIncrementChipOf = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lblIncrementChipOf.setObjectName("lblIncrementChipOf")
        self.gridLayout.addWidget(self.lblIncrementChipOf, 1, 1, 1, 1)
        self.lblDesiredId = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lblDesiredId.setObjectName("lblDesiredId")
        self.gridLayout.addWidget(self.lblDesiredId, 3, 3, 1, 1)
        self.btnResetChipIDs = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnResetChipIDs.setObjectName("btnResetChipIDs")
        self.gridLayout.addWidget(self.btnResetChipIDs, 0, 0, 1, 1)
        self.txtChipIDIncr = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.txtChipIDIncr.setMaximumSize(QtCore.QSize(16777215, 24))
        self.txtChipIDIncr.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtChipIDIncr.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtChipIDIncr.setObjectName("txtChipIDIncr")
        self.gridLayout.addWidget(self.txtChipIDIncr, 1, 2, 1, 1)
        self.txtChipIDDecr = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.txtChipIDDecr.setMaximumSize(QtCore.QSize(16777215, 24))
        self.txtChipIDDecr.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtChipIDDecr.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtChipIDDecr.setObjectName("txtChipIDDecr")
        self.gridLayout.addWidget(self.txtChipIDDecr, 2, 2, 1, 1)
        self.txtChipIDCurrent = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.txtChipIDCurrent.setMaximumSize(QtCore.QSize(16777215, 24))
        self.txtChipIDCurrent.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtChipIDCurrent.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtChipIDCurrent.setObjectName("txtChipIDCurrent")
        self.gridLayout.addWidget(self.txtChipIDCurrent, 3, 2, 1, 1)
        self.lblSetChipOf = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lblSetChipOf.setObjectName("lblSetChipOf")
        self.gridLayout.addWidget(self.lblSetChipOf, 3, 1, 1, 1)
        self.btnSetChipID = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnSetChipID.setObjectName("btnSetChipID")
        self.gridLayout.addWidget(self.btnSetChipID, 3, 0, 1, 1)
        self.txtChipIDDesired = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.txtChipIDDesired.setMaximumSize(QtCore.QSize(16777215, 24))
        self.txtChipIDDesired.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtChipIDDesired.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtChipIDDesired.setObjectName("txtChipIDDesired")
        self.gridLayout.addWidget(self.txtChipIDDesired, 3, 4, 1, 1)
        self.btnShowTestPattern = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnShowTestPattern.setObjectName("btnShowTestPattern")
        self.gridLayout.addWidget(self.btnShowTestPattern, 4, 0, 1, 1)
        self.lblTestOn = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lblTestOn.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblTestOn.setObjectName("lblTestOn")
        self.gridLayout.addWidget(self.lblTestOn, 4, 1, 1, 1)
        self.txtTestOn = QtWidgets.QTextEdit(self.gridLayoutWidget)
        self.txtTestOn.setMaximumSize(QtCore.QSize(16777215, 24))
        self.txtTestOn.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtTestOn.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtTestOn.setObjectName("txtTestOn")
        self.gridLayout.addWidget(self.txtTestOn, 4, 2, 1, 1)
        self.btnStopGuessing = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.btnStopGuessing.setObjectName("btnStopGuessing")
        self.gridLayout.addWidget(self.btnStopGuessing, 4, 4, 1, 1)
        self.lblFWU = QtWidgets.QLabel(self.tabFirmware)
        self.lblFWU.setGeometry(QtCore.QRect(10, 190, 491, 16))
        self.lblFWU.setObjectName("lblFWU")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.tabFirmware)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 210, 491, 121))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.comboBox = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.comboBox.setEnabled(False)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout.addWidget(self.comboBox)
        self.lblFWUCOMPort = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.lblFWUCOMPort.setEnabled(False)
        self.lblFWUCOMPort.setObjectName("lblFWUCOMPort")
        self.horizontalLayout.addWidget(self.lblFWUCOMPort)
        self.comboBox_2 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.comboBox_2.setEnabled(False)
        self.comboBox_2.setObjectName("comboBox_2")
        self.horizontalLayout.addWidget(self.comboBox_2)
        self.gridLayout_2.addLayout(self.horizontalLayout, 2, 1, 1, 1)
        self.comboBox_3 = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.comboBox_3.setEnabled(False)
        self.comboBox_3.setEditable(True)
        self.comboBox_3.setObjectName("comboBox_3")
        self.gridLayout_2.addWidget(self.comboBox_3, 0, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_4.setEnabled(False)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_3.setEnabled(False)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.lblFWUProgrammer = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.lblFWUProgrammer.setEnabled(False)
        self.lblFWUProgrammer.setObjectName("lblFWUProgrammer")
        self.gridLayout_2.addWidget(self.lblFWUProgrammer, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_2.setEnabled(False)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.txtChipIDIncr_2 = QtWidgets.QTextEdit(self.gridLayoutWidget_2)
        self.txtChipIDIncr_2.setEnabled(False)
        self.txtChipIDIncr_2.setMaximumSize(QtCore.QSize(16777215, 24))
        self.txtChipIDIncr_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtChipIDIncr_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.txtChipIDIncr_2.setObjectName("txtChipIDIncr_2")
        self.gridLayout_2.addWidget(self.txtChipIDIncr_2, 1, 1, 1, 1)
        self.btnFindHexFile = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.btnFindHexFile.setEnabled(False)
        self.btnFindHexFile.setObjectName("btnFindHexFile")
        self.gridLayout_2.addWidget(self.btnFindHexFile, 0, 2, 1, 1)
        self.btnFindAvrdude = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.btnFindAvrdude.setEnabled(False)
        self.btnFindAvrdude.setObjectName("btnFindAvrdude")
        self.gridLayout_2.addWidget(self.btnFindAvrdude, 1, 2, 1, 1)
        self.tabWidget.addTab(self.tabFirmware, "")
        self.tabSimulator = QtWidgets.QWidget()
        self.tabSimulator.setObjectName("tabSimulator")
        self.lblComingSoon3 = QtWidgets.QLabel(self.tabSimulator)
        self.lblComingSoon3.setGeometry(QtCore.QRect(30, 30, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lblComingSoon3.setFont(font)
        self.lblComingSoon3.setObjectName("lblComingSoon3")
        self.tabWidget.addTab(self.tabSimulator, "")
        self.tabBaudRate = QtWidgets.QWidget()
        self.tabBaudRate.setObjectName("tabBaudRate")
        self.lblComingSoon4 = QtWidgets.QLabel(self.tabBaudRate)
        self.lblComingSoon4.setGeometry(QtCore.QRect(30, 30, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lblComingSoon4.setFont(font)
        self.lblComingSoon4.setObjectName("lblComingSoon4")
        self.tabWidget.addTab(self.tabBaudRate, "")
        self.groupMarqueeProps = QtWidgets.QGroupBox(self.centralwidget)
        self.groupMarqueeProps.setGeometry(QtCore.QRect(10, 20, 191, 161))
        self.groupMarqueeProps.setObjectName("groupMarqueeProps")
        self.spinRows = QtWidgets.QSpinBox(self.groupMarqueeProps)
        self.spinRows.setEnabled(False)
        self.spinRows.setGeometry(QtCore.QRect(50, 20, 42, 22))
        self.spinRows.setMinimum(1)
        self.spinRows.setMaximum(128)
        self.spinRows.setObjectName("spinRows")
        self.lblDisplayRows = QtWidgets.QLabel(self.groupMarqueeProps)
        self.lblDisplayRows.setEnabled(False)
        self.lblDisplayRows.setGeometry(QtCore.QRect(10, 20, 31, 16))
        self.lblDisplayRows.setObjectName("lblDisplayRows")
        self.chkMultiplexed = QtWidgets.QCheckBox(self.groupMarqueeProps)
        self.chkMultiplexed.setEnabled(False)
        self.chkMultiplexed.setGeometry(QtCore.QRect(100, 20, 81, 17))
        self.chkMultiplexed.setObjectName("chkMultiplexed")
        self.lblPanelsPerRow = QtWidgets.QLabel(self.groupMarqueeProps)
        self.lblPanelsPerRow.setGeometry(QtCore.QRect(10, 50, 81, 16))
        self.lblPanelsPerRow.setObjectName("lblPanelsPerRow")
        self.spinPanelsPerRow = QtWidgets.QSpinBox(self.groupMarqueeProps)
        self.spinPanelsPerRow.setGeometry(QtCore.QRect(100, 50, 42, 22))
        self.spinPanelsPerRow.setMinimum(1)
        self.spinPanelsPerRow.setMaximum(64)
        self.spinPanelsPerRow.setProperty("value", 2)
        self.spinPanelsPerRow.setObjectName("spinPanelsPerRow")
        self.label = QtWidgets.QLabel(self.groupMarqueeProps)
        self.label.setGeometry(QtCore.QRect(10, 80, 101, 16))
        self.label.setObjectName("label")
        self.spinUpdateDelay = QtWidgets.QSpinBox(self.groupMarqueeProps)
        self.spinUpdateDelay.setGeometry(QtCore.QRect(110, 80, 42, 22))
        self.spinUpdateDelay.setMinimum(1)
        self.spinUpdateDelay.setMaximum(1000)
        self.spinUpdateDelay.setProperty("value", 60)
        self.spinUpdateDelay.setObjectName("spinUpdateDelay")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 543, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(5)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "LEDgoes PC Interface"))
        MainWindow.setToolTip(_translate("MainWindow", "How many milliseconds the program will pause before sending the next wave of serial data to the marquee"))
        self.gridGroupBox.setTitle(_translate("MainWindow", "Communication Properties"))
        self.lblRow2COMPort.setText(_translate("MainWindow", "Row 2 COM Port:"))
        self.lblRow1COMPort.setText(_translate("MainWindow", "Row 1 COM Port:"))
        self.lblSpeed.setText(_translate("MainWindow", "Speed (bps):"))
        self.btnConnectRow1.setText(_translate("MainWindow", "Connect"))
        self.btnConnectRow2.setText(_translate("MainWindow", "Connect"))
        self.btnChangeBaudRate.setToolTip(_translate("MainWindow", "You don\'t need to click this until you have already opened the serial connection."))
        self.btnChangeBaudRate.setText(_translate("MainWindow", "Change"))
        self.lblRawTextInstrs.setText(_translate("MainWindow", "Enter a message in the box at the bottom, then hit Push.  It will appear in the list below, and on the LED matrix after the current cycle has completed."))
        self.btnPush.setText(_translate("MainWindow", "Push"))
        self.btnReplace.setText(_translate("MainWindow", "Replace"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabRawText), _translate("MainWindow", "Raw Text"))
        self.lblComingSoon1.setText(_translate("MainWindow", "Coming Soon"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabTwitter), _translate("MainWindow", "Twitter Feed"))
        self.lblComingSoon2.setText(_translate("MainWindow", "Coming Soon"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabAnimation), _translate("MainWindow", "Animation"))
        self.lblFirmwareDescription.setText(_translate("MainWindow", "Send commands to your boards in order to exert finer control over them."))
        self.btnDecrementChipID.setText(_translate("MainWindow", "Decrement A Chip ID"))
        self.lblDecrementChipOf.setText(_translate("MainWindow", "Current ID:"))
        self.btnIncrementChipID.setText(_translate("MainWindow", "Increment A Chip ID"))
        self.lblIncrementChipOf.setText(_translate("MainWindow", "Current ID:"))
        self.lblDesiredId.setText(_translate("MainWindow", "Desired ID:"))
        self.btnResetChipIDs.setText(_translate("MainWindow", "Reset All Chip IDs"))
        self.lblSetChipOf.setText(_translate("MainWindow", "Current ID:"))
        self.btnSetChipID.setText(_translate("MainWindow", "Set A Chip ID"))
        self.btnShowTestPattern.setText(_translate("MainWindow", "Show Test Pattern"))
        self.lblTestOn.setText(_translate("MainWindow", "On:"))
        self.btnStopGuessing.setText(_translate("MainWindow", "Let Me Stop Guessing!"))
        self.lblFWU.setText(_translate("MainWindow", "Update the firmware on your boards here."))
        self.lblFWUCOMPort.setText(_translate("MainWindow", "Port:"))
        self.label_4.setText(_translate("MainWindow", "avrdude command:"))
        self.label_3.setText(_translate("MainWindow", "Path to avrdude:"))
        self.lblFWUProgrammer.setText(_translate("MainWindow", "Programmer:"))
        self.label_2.setText(_translate("MainWindow", "Path to .HEX file:"))
        self.btnFindHexFile.setText(_translate("MainWindow", "..."))
        self.btnFindAvrdude.setText(_translate("MainWindow", "..."))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabFirmware), _translate("MainWindow", "Firmware"))
        self.lblComingSoon3.setText(_translate("MainWindow", "Coming Soon"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSimulator), _translate("MainWindow", "Simulator"))
        self.lblComingSoon4.setText(_translate("MainWindow", "Coming Soon"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabBaudRate), _translate("MainWindow", "Baud Rate"))
        self.groupMarqueeProps.setTitle(_translate("MainWindow", "Marquee Properties"))
        self.lblDisplayRows.setText(_translate("MainWindow", "Rows:"))
        self.chkMultiplexed.setText(_translate("MainWindow", "Multiplexed"))
        self.lblPanelsPerRow.setText(_translate("MainWindow", "Panels Per Row:"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p>Update Delay (ms):</p></body></html>"))

