# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Stephen\Documents\LEDgoes PC Interface.ui'
#
# Created: Sun Feb 02 22:25:57 2014
#      by: PyQt5 UI code generator 5.1.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(543, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.rowsFrame = QtWidgets.QFrame(self.centralwidget)
        self.rowsFrame.setGeometry(QtCore.QRect(30, 30, 120, 80))
        self.rowsFrame.setFrameShape(QtWidgets.QFrame.Box)
        self.rowsFrame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.rowsFrame.setObjectName("rowsFrame")
        self.spinRows = QtWidgets.QSpinBox(self.rowsFrame)
        self.spinRows.setGeometry(QtCore.QRect(10, 10, 42, 22))
        self.spinRows.setMinimum(1)
        self.spinRows.setMaximum(128)
        self.spinRows.setObjectName("spinRows")
        self.chkMultiplexed = QtWidgets.QCheckBox(self.rowsFrame)
        self.chkMultiplexed.setGeometry(QtCore.QRect(10, 40, 81, 17))
        self.chkMultiplexed.setObjectName("chkMultiplexed")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(130, 30, 271, 91))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.lblSpeed = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lblSpeed.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblSpeed.setObjectName("lblSpeed")
        self.gridLayout.addWidget(self.lblSpeed, 0, 0, 1, 1)
        self.selSpeed = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.selSpeed.setObjectName("selSpeed")
        self.gridLayout.addWidget(self.selSpeed, 0, 1, 1, 1)
        self.lblRow1COMPort = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lblRow1COMPort.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblRow1COMPort.setObjectName("lblRow1COMPort")
        self.gridLayout.addWidget(self.lblRow1COMPort, 1, 0, 1, 1)
        self.lblRow2COMPort = QtWidgets.QLabel(self.gridLayoutWidget)
        self.lblRow2COMPort.setEnabled(False)
        self.lblRow2COMPort.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblRow2COMPort.setObjectName("lblRow2COMPort")
        self.gridLayout.addWidget(self.lblRow2COMPort, 2, 0, 1, 1)
        self.selRow1COM = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.selRow1COM.setObjectName("selRow1COM")
        self.gridLayout.addWidget(self.selRow1COM, 1, 1, 1, 1)
        self.selRow2COM = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.selRow2COM.setEnabled(False)
        self.selRow2COM.setObjectName("selRow2COM")
        self.gridLayout.addWidget(self.selRow2COM, 2, 1, 1, 1)
        self.btnConnectRow1 = QtWidgets.QPushButton(self.centralwidget)
        self.btnConnectRow1.setGeometry(QtCore.QRect(420, 60, 75, 23))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(170, 255, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.btnConnectRow1.setPalette(palette)
        self.btnConnectRow1.setObjectName("btnConnectRow1")
        self.btnConnectRow2 = QtWidgets.QPushButton(self.centralwidget)
        self.btnConnectRow2.setEnabled(False)
        self.btnConnectRow2.setGeometry(QtCore.QRect(420, 90, 75, 23))
        self.btnConnectRow2.setObjectName("btnConnectRow2")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 150, 521, 401))
        self.tabWidget.setObjectName("tabWidget")
        self.tabRawText = QtWidgets.QWidget()
        self.tabRawText.setObjectName("tabRawText")
        self.lblRawTextInstrs = QtWidgets.QLabel(self.tabRawText)
        self.lblRawTextInstrs.setGeometry(QtCore.QRect(20, 20, 471, 31))
        self.lblRawTextInstrs.setWordWrap(True)
        self.lblRawTextInstrs.setObjectName("lblRawTextInstrs")
        self.textEdit = QtWidgets.QTextEdit(self.tabRawText)
        self.textEdit.setGeometry(QtCore.QRect(20, 330, 311, 21))
        self.textEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit.setObjectName("textEdit")
        self.btnPush = QtWidgets.QPushButton(self.tabRawText)
        self.btnPush.setGeometry(QtCore.QRect(340, 330, 75, 23))
        self.btnPush.setObjectName("btnPush")
        self.btnReplace = QtWidgets.QPushButton(self.tabRawText)
        self.btnReplace.setGeometry(QtCore.QRect(420, 330, 75, 23))
        self.btnReplace.setObjectName("btnReplace")
        self.tabWidget.addTab(self.tabRawText, "")
        self.tabTwitter = QtWidgets.QWidget()
        self.tabTwitter.setObjectName("tabTwitter")
        self.tabWidget.addTab(self.tabTwitter, "")
        self.tabAnimation = QtWidgets.QWidget()
        self.tabAnimation.setObjectName("tabAnimation")
        self.tabWidget.addTab(self.tabAnimation, "")
        self.tabSimulator = QtWidgets.QWidget()
        self.tabSimulator.setObjectName("tabSimulator")
        self.tabWidget.addTab(self.tabSimulator, "")
        self.tabBaudRate = QtWidgets.QWidget()
        self.tabBaudRate.setObjectName("tabBaudRate")
        self.tabWidget.addTab(self.tabBaudRate, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 543, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "LEDgoes PC Interface"))
        self.chkMultiplexed.setText(_translate("MainWindow", "Multiplexed"))
        self.lblSpeed.setText(_translate("MainWindow", "Speed (bps):"))
        self.lblRow1COMPort.setText(_translate("MainWindow", "Row 1 COM Port:"))
        self.lblRow2COMPort.setText(_translate("MainWindow", "Row 2 COM Port:"))
        self.btnConnectRow1.setText(_translate("MainWindow", "Connect"))
        self.btnConnectRow2.setText(_translate("MainWindow", "Connect"))
        self.lblRawTextInstrs.setText(_translate("MainWindow", "Enter a message in the box at the bottom, then hit Push.  It will appear in the list below, and on the LED matrix after the current cycle has completed."))
        self.btnPush.setText(_translate("MainWindow", "Push"))
        self.btnReplace.setText(_translate("MainWindow", "Replace"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabRawText), _translate("MainWindow", "Raw Text"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabTwitter), _translate("MainWindow", "Twitter Feed"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabAnimation), _translate("MainWindow", "Animation"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabSimulator), _translate("MainWindow", "Simulator"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabBaudRate), _translate("MainWindow", "Baud Rate"))

